# Generated by Django 5.1.6 on 2025-06-11 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_waterconsumption'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankFlowMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(help_text='Value of the metric (liters for tank level, liters/min for flow rates)')),
                ('metric_type', models.CharField(choices=[('tank_level', 'Tank Level'), ('main_flow_rate', 'Main Flow Rate'), ('secondary_flow_rate', 'Secondary Flow Rate')], help_text='Type of metric (tank_level, main_flow_rate, secondary_flow_rate)', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time the reading was recorded')),
                ('sensor_id', models.CharField(help_text="Unique identifier for the sensor (e.g., 'tank_level_sensor')", max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_flow_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'metric_type', 'timestamp'], name='core_tankfl_user_id_bf6a5e_idx'), models.Index(fields=['sensor_id'], name='core_tankfl_sensor__5ef6c5_idx')],
            },
        ),
    ]
