# Generated by Django 5.1.6 on 2025-06-11 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tankflowmetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeakageDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(help_text='True if sensor detects motion (PIR) or leakage (alarm)')),
                ('detection_type', models.CharField(choices=[('first_pir', 'First PIR Sensor'), ('second_pir', 'Second PIR Sensor'), ('leak_alarm', 'Leak Alarm')], help_text='Type of detection (first_pir, second_pir, leak_alarm)', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time the reading was recorded')),
                ('sensor_id', models.CharField(help_text="Unique identifier for the sensor (e.g., 'first_pir_sensor')", max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leakage_detections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'detection_type', 'timestamp'], name='core_leakag_user_id_c37be2_idx'), models.Index(fields=['sensor_id'], name='core_leakag_sensor__2c44a6_idx')],
            },
        ),
    ]
