# Generated by Django 5.1.6 on 2025-06-12 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_leakagedetection'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterConsumptionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(help_text='True if alert is triggered')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('minute', 'Minute')], help_text='Time period for alert (daily, weekly, monthly, minute)', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Time the alert was recorded')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'period', 'timestamp'], name='core_waterc_user_id_980a02_idx')],
            },
        ),
        migrations.CreateModel(
            name='WaterConsumptionThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField(help_text='Threshold value in liters')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('minute', 'Minute')], help_text='Time period for threshold (daily, weekly, monthly, minute)', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_thresholds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'period'], name='core_waterc_user_id_a915d3_idx')],
                'unique_together': {('user', 'period')},
            },
        ),
    ]
