# Generated by Django 5.1.6 on 2025-06-23 14:46

import core.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_waterconsumptionalert_waterconsumptionthreshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=12, unique=True, validators=[core.models.base.validate_egyptian_phone_number]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='home_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('homeowner', 'Homeowner'), ('admin', 'Admin')], default='homeowner', max_length=20),
        ),
    ]
