# Generated by Django 5.1.6 on 2025-06-24 02:09

import core.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customuser_phone_number_alter_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[core.models.base.validate_egyptian_phone_number]),
        ),
    ]
