# Generated by Django 5.1.6 on 2025-06-27 11:26

import core.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[core.models.base.validate_egyptian_phone_number]),
        ),
    ]
